services:
  spring_boot:
    container_name: spring_boot
    restart: always
    image: ssove/meetjyou
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=db,secrets
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase-adminsdk.json
      - OCI_AUTH_CONFIG_FILE_PATH=/run/secrets/oci/config
    volumes:
      - ./data/spring_boot/firebase-adminsdk.json:/run/secrets/firebase-adminsdk.json:ro
      - ./data/spring_boot/oci:/run/secrets/oci:ro
    networks:
      - my_network

  nginx:
    image: nginx:1.26.3
    container_name: nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - spring_boot
    networks:
      - my_network

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
