package com.dogGetDrunk.meetjyou.loadtest;

import io.gatling.javaapi.core.ChainBuilder;
import io.gatling.javaapi.core.ScenarioBuilder;
import io.gatling.javaapi.core.Simulation;
import io.gatling.javaapi.http.HttpProtocolBuilder;

import java.time.Duration;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Supplier;
import java.util.stream.Stream;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

// Load test for meetjyou-backend local dev instance.
// Requires: SPRING_PROFILES_ACTIVE=dev,db,secrets, dev.bypass.enabled=true (default in application-dev.yml)
// Run: ./gradlew gatlingRun --simulation com.dogGetDrunk.meetjyou.loadtest.MixedScenarioSimulation
// Override target: ./gradlew gatlingRun --simulation ... -DBASE_URL=http://localhost:8080
//
// Design note vs. the original k6 script: k6's per-VU module state let a VU register once and
// reuse that session across every subsequent iteration for the life of the VU. Gatling's closed
// injection model recycles a fresh session per completed scenario run, so "register once, then
// loop" is reproduced here as register -> during(5m).on(browse/create), i.e. one scenario
// execution that internally loops for (roughly) the total ramp duration below, rather than many
// short scenario executions sharing external state.
public class MixedScenarioSimulation extends Simulation {

    private static final String BASE_URL = System.getProperty("BASE_URL", "http://localhost:8080");

    private static final HttpProtocolBuilder httpProtocol = http.baseUrl(BASE_URL)
            .contentTypeHeader("application/json");

    private static Iterator<Map<String, Object>> registrationFeeder() {
        return Stream.generate((Supplier<Map<String, Object>>) () -> {
            String unique = System.currentTimeMillis() + "" + ThreadLocalRandom.current().nextInt(100_000);
            // nickname is capped at 8 chars server-side.
            String nickname = ("u" + Long.toString(ThreadLocalRandom.current().nextLong() & Long.MAX_VALUE, 36))
                    .substring(0, 8);
            Map<String, Object> row = new HashMap<>();
            row.put("email", "loadtest-vu-" + unique + "@local.test");
            row.put("nickname", nickname);
            return row;
        }).iterator();
    }

    private static final ChainBuilder registerVu = exec(
            http("POST /dev/auth/register")
                    .post("/api/v1/dev/auth/register")
                    .body(StringBody("{\"email\":\"#{email}\",\"nickname\":\"#{nickname}\"}"))
                    .check(status().is(201))
                    .check(jsonPath("$.uuid").saveAs("uuid"))
                    .check(jsonPath("$.accessToken").saveAs("accessToken")));

    private static final ChainBuilder readHeavyBrowsing = group("read-heavy browsing").on(
            exec(http("GET /posts").get("/api/v1/posts?page=0&size=20")
                    .header("Authorization", "Bearer #{accessToken}")
                    .check(status().is(200))),
            exec(http("GET /chat/rooms").get("/api/v1/chat/rooms")
                    .header("Authorization", "Bearer #{accessToken}")
                    .check(status().is(200))),
            // Fresh dev-registered users have no Preference row yet, so /users/me/profile 404s
            // with PREFERENCE_NOT_FOUND until onboarding is completed; use a preference-agnostic
            // endpoint instead so this doesn't register as a false-positive server error.
            exec(http("GET /users/me/posts").get("/api/v1/users/me/posts?page=0&size=10")
                    .header("Authorization", "Bearer #{accessToken}")
                    .check(status().is(200))));

    private static final ChainBuilder createPost = group("write path: create post").on(
            exec(http("POST /posts (create)")
                    .post("/api/v1/posts")
                    .header("Authorization", "Bearer #{accessToken}")
                    .body(StringBody(session -> "{"
                            + "\"title\":\"Load test trip " + session.userId() + "\","
                            + "\"content\":\"Generated by Gatling load test\","
                            + "\"isInstant\":false,"
                            + "\"itinStart\":\"2026-08-01T00:00:00Z\","
                            + "\"itinFinish\":\"2026-08-05T00:00:00Z\","
                            + "\"location\":\"제주\","
                            + "\"capacity\":4}"))
                    .check(status().is(200))));

    private static final ChainBuilder createPlan = group("write path: create plan").on(
            exec(http("POST /plans (create)")
                    .post("/api/v1/plans")
                    .header("Authorization", "Bearer #{accessToken}")
                    .body(StringBody(session -> "{"
                            + "\"title\":\"Plan " + session.userId() + "\","
                            + "\"itinStart\":\"2026-08-01T00:00:00Z\","
                            + "\"itinFinish\":\"2026-08-05T00:00:00Z\","
                            + "\"location\":\"제주\","
                            + "\"centerLat\":33.4996,"
                            + "\"centerLng\":126.5312,"
                            + "\"markers\":[]}"))
                    .check(status().is(200))));

    private static final ScenarioBuilder scn = scenario("Mixed scenario")
            .feed(registrationFeeder())
            .exec(registerVu)
            .during(Duration.ofMinutes(5)).on(
                    readHeavyBrowsing,
                    pause(Duration.ZERO, Duration.ofMillis(1500)),
                    createPost,
                    pause(Duration.ZERO, Duration.ofMillis(1500)),
                    createPlan,
                    pause(Duration.ZERO, Duration.ofSeconds(2)));

    {
        setUp(scn.injectClosed(
                rampConcurrentUsers(0).to(20).during(Duration.ofSeconds(30)),
                constantConcurrentUsers(20).during(Duration.ofMinutes(1)),
                rampConcurrentUsers(20).to(50).during(Duration.ofSeconds(30)),
                constantConcurrentUsers(50).during(Duration.ofMinutes(1)),
                rampConcurrentUsers(50).to(100).during(Duration.ofSeconds(30)),
                constantConcurrentUsers(100).during(Duration.ofMinutes(1)),
                rampConcurrentUsers(100).to(0).during(Duration.ofSeconds(30))))
                .protocols(httpProtocol)
                .assertions(
                        global().responseTime().percentile(95.0).lt(800),
                        global().failedRequests().percent().lt(5.0));
    }
}
