logging:
  level:
    org.springframework.security: DEBUG

spring:
  flyway:
    clean-enabled: true

dev:
  bypass:
    enabled: true

app:
  websocket:
    allowed-origin-patterns:
      - "http://localhost:*"
      - "http://127.0.0.1:*"
