logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: trace

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true

dev:
  bypass:
    enabled: true

app:
  websocket:
    allowed-origin-patterns:
      - "http://localhost:*"
      - "http://127.0.0.1:*"
