spring:
  application:
    name: meetjyou
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

springdoc:
  swagger-ui:
    path: /api-doc  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
#    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
  paths-to-match:
    - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG

server:
  forward-headers-strategy: native

jwt:
  issuer: ${JWT_ISSUER}
  access-expiration: ${JWT_AT_EXP} # 30분
  refresh-expiration: ${JWT_RT_EXP} # 30일
  secret-key: ${JWT_SECRET_KEY} # 256 bits for HS256

dns:
  url: ${DNS_URL}

oracle:
  oci:
    bucketName: ${OCI_BUCKET_NAME}
    namespace: ${OCI_NAMESPACE}
