ALTER TABLE plan
    ADD COLUMN title VARCHAR(20) NOT NULL DEFAULT '' AFTER uuid,
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER owner_id,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_at;
